name: Build and Test x16-PRos

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build x16-PRos
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y nasm mtools dosfstools

      - name: Run build script
        run: |
          set -euxo pipefail
          chmod +x build.sh
          ./build.sh

      - name: Check output files
        run: |
          set -euo pipefail
          [[ -f bin/BOOT.BIN ]] || { echo "Missing bin/BOOT.BIN"; exit 1; }
          [[ -f bin/KERNEL.BIN ]] || { echo "Missing bin/KERNEL.BIN"; exit 1; }
          [[ -f disk_img/x16pros.img ]] || { echo "Missing disk_img/x16pros.img"; exit 1; }
          echo "All required files were built."

      - name: Prepare artifacts
        run: |
          set -euxo pipefail
          mkdir -p out
          cp disk_img/x16pros.img out/x16pros.img
          cp bin/BOOT.BIN out/BOOT.BIN
          cp bin/KERNEL.BIN out/KERNEL.BIN
          (cd out && sha256sum x16pros.img BOOT.BIN KERNEL.BIN > SHA256SUMS)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x16pros-build-${{ github.run_number }}
          path: out/*
          retention-days: 7