name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y nasm mtools dosfstools

      - name: Build
        run: |
          set -euxo pipefail
          chmod +x build.sh
          ./build.sh

      - name: Prepare artifacts
        run: |
          set -euxo pipefail
          mkdir -p out
          cp disk_img/x16pros.img out/x16pros.img
          cp bin/BOOT.BIN out/BOOT.BIN
          cp bin/KERNEL.BIN out/KERNEL.BIN
          (cd out && sha256sum x16pros.img BOOT.BIN KERNEL.BIN > SHA256SUMS)

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            out/x16pros.img
            out/BOOT.BIN
            out/KERNEL.BIN
            out/SHA256SUMS